name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # รูปที่ 1: ปฏิทิน 3 มิติ (ฝั่งซ้าย)
      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # รูปที่ 2: ภาษาแบบเจาะลึก (ฝั่งขวา)
      - name: Indepth Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
